// 상수 및 목업 데이터 파일 - 테스트용 골프 코스, 사용자, 예약 데이터
// File hằng số và dữ liệu giả - dữ liệu sân golf, người dùng, đặt chỗ để test
// Constants and mock data file - golf courses, user, and booking data for testing

import { Course, Booking, User } from './types';

// 목업 골프 코스 데이터 - 베트남 주요 골프장 정보
// Dữ liệu giả sân golf - thông tin các sân golf chính tại Việt Nam
// Mock golf course data - information about major golf courses in Vietnam
export const MOCK_COURSES: Course[] = [
  // === HÀ NỘI GOLF COURSES (10) ===
  {
    id: 'hn1',
    name: 'King\'s Island Golf Resort',
    location: 'Dong Mo Lake, Son Tay',
    city: 'Hanoi',
    holes: 36,
    par: 144,
    yards: 14500,
    type: 'Mountain',
    rating: 4.8,
    reviews: 342,
    price: 2800000,
    image: '/images/twin-doves.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'hn2',
    name: 'BRG Kings Island Golf Resort',
    location: 'Dong Mo, Son Tay',
    city: 'Hanoi',
    holes: 36,
    par: 144,
    yards: 14200,
    type: 'Lakeside',
    rating: 4.9,
    reviews: 456,
    price: 3200000,
    image: '/images/da-nang.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'hn3',
    name: 'Sky Lake Resort & Golf Club',
    location: 'Chuong My District',
    city: 'Hanoi',
    holes: 36,
    par: 144,
    yards: 14800,
    type: 'Parkland',
    rating: 4.7,
    reviews: 287,
    price: 2500000,
    originalPrice: 2800000,
    image: '/images/hoiana.png',
    deal: '-10% DEAL',
    verified: true
  },
  {
    id: 'hn4',
    name: 'Long Bien Golf Course',
    location: 'Long Bien District',
    city: 'Hanoi',
    holes: 27,
    par: 108,
    yards: 10500,
    type: 'Urban',
    rating: 4.5,
    reviews: 198,
    price: 1800000,
    image: '/images/the-bluffs.png',
    verified: true
  },
  {
    id: 'hn5',
    name: 'Hanoi Golf Club',
    subName: 'Legacy Course',
    location: 'My Dinh, Nam Tu Liem',
    city: 'Hanoi',
    holes: 18,
    par: 72,
    yards: 7200,
    type: 'Parkland',
    rating: 4.6,
    reviews: 523,
    price: 2200000,
    image: '/images/tan-son-nhat.png',
    verified: true
  },
  {
    id: 'hn6',
    name: 'Phoenix Golf Resort',
    location: 'Dan Phuong District',
    city: 'Hanoi',
    holes: 18,
    par: 72,
    yards: 6950,
    type: 'Resort',
    rating: 4.7,
    reviews: 234,
    price: 2600000,
    image: '/images/twin-doves.png',
    isRecommended: true
  },
  {
    id: 'hn7',
    name: 'Chi Linh Star Golf & Country Club',
    location: 'Chi Linh, Hai Duong',
    city: 'Hanoi',
    holes: 27,
    par: 108,
    yards: 11000,
    type: 'Championship',
    rating: 4.8,
    reviews: 167,
    price: 2900000,
    image: '/images/da-nang.png',
    verified: true
  },
  {
    id: 'hn8',
    name: 'Tam Dao Golf Resort',
    location: 'Tam Dao, Vinh Phuc',
    city: 'Hanoi',
    holes: 18,
    par: 72,
    yards: 7100,
    type: 'Mountain',
    rating: 4.6,
    reviews: 145,
    price: 2400000,
    originalPrice: 2700000,
    image: '/images/hoiana.png',
    deal: '-11% TODAY'
  },
  {
    id: 'hn9',
    name: 'Van Tri Golf Club',
    location: 'Gia Lam District',
    city: 'Hanoi',
    holes: 27,
    par: 108,
    yards: 10800,
    type: 'Traditional',
    rating: 4.5,
    reviews: 189,
    price: 2100000,
    image: '/images/the-bluffs.png',
    verified: true
  },
  {
    id: 'hn10',
    name: 'Dong Mo Golf & Resort',
    location: 'Son Tay, Hanoi',
    city: 'Hanoi',
    holes: 18,
    par: 72,
    yards: 6800,
    type: 'Lakeside',
    rating: 4.4,
    reviews: 156,
    price: 1900000,
    image: '/images/tan-son-nhat.png'
  },

  // === HỒ CHÍ MINH GOLF COURSES (10) ===
  {
    id: 'hcm1',
    name: 'Tan Son Nhat Golf Course',
    location: '6 Tan Son, Ward 12, Go Vap',
    city: 'Ho Chi Minh City',
    holes: 36,
    par: 144,
    yards: 14200,
    type: 'Urban',
    rating: 4.7,
    reviews: 512,
    price: 2500000,
    image: '/images/tan-son-nhat.png',
    verified: true
  },
  {
    id: 'hcm2',
    name: 'Song Be Golf Resort',
    location: 'Thu Duc City',
    city: 'Ho Chi Minh City',
    holes: 27,
    par: 108,
    yards: 11200,
    type: 'Parkland',
    rating: 4.8,
    reviews: 423,
    price: 2700000,
    image: '/images/twin-doves.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'hcm3',
    name: 'Vietnam Golf & Country Club',
    subName: 'West Course',
    location: 'Thu Duc City',
    city: 'Ho Chi Minh City',
    holes: 36,
    par: 144,
    yards: 14600,
    type: 'Championship',
    rating: 4.9,
    reviews: 678,
    price: 3500000,
    image: '/images/da-nang.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'hcm4',
    name: 'Long Thanh Golf Club',
    location: 'Long Thanh, Dong Nai',
    city: 'Ho Chi Minh City',
    holes: 36,
    par: 144,
    yards: 14400,
    type: 'Resort',
    rating: 4.7,
    reviews: 334,
    price: 2800000,
    originalPrice: 3100000,
    image: '/images/hoiana.png',
    deal: '-10% DEAL',
    verified: true
  },
  {
    id: 'hcm5',
    name: 'Saigon Golf Club',
    location: 'District 9, Thu Duc City',
    city: 'Ho Chi Minh City',
    holes: 18,
    par: 72,
    yards: 7150,
    type: 'Parkland',
    rating: 4.6,
    reviews: 267,
    price: 2400000,
    image: '/images/the-bluffs.png',
    verified: true
  },
  {
    id: 'hcm6',
    name: 'Twin Doves Golf Club',
    location: 'Binh Duong Province',
    city: 'Ho Chi Minh City',
    holes: 18,
    par: 72,
    yards: 7100,
    type: 'Parkland',
    rating: 4.9,
    reviews: 245,
    price: 3500000,
    image: '/images/twin-doves.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'hcm7',
    name: 'Dong Nai Golf Resort',
    location: 'Bien Hoa, Dong Nai',
    city: 'Ho Chi Minh City',
    holes: 27,
    par: 108,
    yards: 10900,
    type: 'Traditional',
    rating: 4.5,
    reviews: 198,
    price: 2200000,
    image: '/images/tan-son-nhat.png',
    verified: true
  },
  {
    id: 'hcm8',
    name: 'Viet Nam Golf Club',
    location: 'Binh Chanh District',
    city: 'Ho Chi Minh City',
    holes: 18,
    par: 72,
    yards: 6900,
    type: 'Traditional',
    rating: 4.4,
    reviews: 156,
    price: 2000000,
    originalPrice: 2300000,
    image: '/images/da-nang.png',
    deal: '-13% SALE'
  },
  {
    id: 'hcm9',
    name: 'Sonadezi Long Thanh Golf Club',
    location: 'Long Thanh, Dong Nai',
    city: 'Ho Chi Minh City',
    holes: 27,
    par: 108,
    yards: 11000,
    type: 'Championship',
    rating: 4.7,
    reviews: 289,
    price: 2600000,
    image: '/images/hoiana.png',
    verified: true
  },
  {
    id: 'hcm10',
    name: 'Phu My Golf Resort',
    location: 'Ba Ria - Vung Tau',
    city: 'Ho Chi Minh City',
    holes: 18,
    par: 72,
    yards: 7050,
    type: 'Coastal',
    rating: 4.8,
    reviews: 234,
    price: 3200000,
    image: '/images/the-bluffs.png',
    isRecommended: true,
    verified: true
  },

  // === ĐÀ NẴNG GOLF COURSES (10) ===
  {
    id: 'dn1',
    name: 'Da Nang Golf Resort',
    subName: 'Greg Norman Course',
    location: 'Hoa Hai Ward, Ngu Hanh Son',
    city: 'Da Nang',
    holes: 18,
    par: 72,
    yards: 7160,
    type: 'Dunes',
    rating: 4.8,
    reviews: 324,
    price: 2200000,
    originalPrice: 2400000,
    image: '/images/da-nang.png',
    deal: '-15% TODAY',
    verified: true
  },
  {
    id: 'dn2',
    name: 'Hoiana Shores Golf Club',
    location: 'Quang Nam Province',
    city: 'Da Nang',
    holes: 18,
    par: 72,
    yards: 7004,
    type: 'Links',
    rating: 4.9,
    reviews: 289,
    price: 3500000,
    image: '/images/hoiana.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'dn3',
    name: 'BRG Da Nang Golf Resort',
    subName: 'Norman + Nicklaus',
    location: 'Hoa Hai, Ngu Hanh Son',
    city: 'Da Nang',
    holes: 36,
    par: 144,
    yards: 14500,
    type: 'Coastal',
    rating: 4.9,
    reviews: 456,
    price: 3800000,
    image: '/images/twin-doves.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'dn4',
    name: 'Laguna Lang Co Golf Club',
    location: 'Phu Loc, Thua Thien Hue',
    city: 'Da Nang',
    holes: 18,
    par: 71,
    yards: 7050,
    type: 'Links',
    rating: 4.8,
    reviews: 267,
    price: 3300000,
    image: '/images/the-bluffs.png',
    verified: true
  },
  {
    id: 'dn5',
    name: 'Montgomerie Links',
    location: 'Dien Ban, Quang Nam',
    city: 'Da Nang',
    holes: 36,
    par: 144,
    yards: 14200,
    type: 'Links',
    rating: 4.7,
    reviews: 198,
    price: 2900000,
    originalPrice: 3200000,
    image: '/images/tan-son-nhat.png',
    deal: '-9% DEAL',
    verified: true
  },
  {
    id: 'dn6',
    name: 'Ba Na Hills Golf Club',
    location: 'Hoa Ninh, Hoa Vang',
    city: 'Da Nang',
    holes: 18,
    par: 72,
    yards: 7050,
    type: 'Mountain',
    rating: 4.8,
    reviews: 345,
    price: 3000000,
    image: '/images/da-nang.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'dn7',
    name: 'Diamond Bay Golf & Villas',
    location: 'Ngu Hanh Son District',
    city: 'Da Nang',
    holes: 18,
    par: 72,
    yards: 6900,
    type: 'Resort',
    rating: 4.6,
    reviews: 234,
    price: 2600000,
    image: '/images/hoiana.png',
    verified: true
  },
  {
    id: 'dn8',
    name: 'Vinpearl Golf Nam Hoi An',
    location: 'Duy Xuyen, Quang Nam',
    city: 'Da Nang',
    holes: 36,
    par: 144,
    yards: 14700,
    type: 'Championship',
    rating: 4.9,
    reviews: 412,
    price: 3600000,
    image: '/images/twin-doves.png',
    isRecommended: true,
    verified: true
  },
  {
    id: 'dn9',
    name: 'FLC Quy Nhon Golf Links',
    location: 'Quy Nhon, Binh Dinh',
    city: 'Da Nang',
    holes: 36,
    par: 144,
    yards: 14300,
    type: 'Links',
    rating: 4.7,
    reviews: 178,
    price: 3100000,
    originalPrice: 3500000,
    image: '/images/the-bluffs.png',
    deal: '-11% OFF',
    verified: true
  },
  {
    id: 'dn10',
    name: 'Danang Golf Club',
    location: 'Cam Le District',
    city: 'Da Nang',
    holes: 27,
    par: 108,
    yards: 10900,
    type: 'Parkland',
    rating: 4.5,
    reviews: 156,
    price: 2300000,
    image: '/images/tan-son-nhat.png',
    verified: true
  }
];

// 목업 사용자 데이터 - 한국인 골퍼 프로필
// Dữ liệu giả người dùng - hồ sơ golfer người Hàn
// Mock user data - Korean golfer profile
export const MOCK_USER: User = {
  name: 'Kim Min-jun',
  tier: 'Gold Tier',
  points: 1450,
  avatar: 'https://picsum.photos/seed/golf/100/100'
};

// 목업 예약 데이터 - 사용자의 과거 및 예정된 예약
// Dữ liệu giả đặt chỗ - các đặt chỗ đã qua và sắp tới của người dùng
// Mock booking data - user's past and upcoming bookings
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    courseId: 'hcm6',
    date: 'Oct 24, 2023',
    time: '08:00 AM',
    players: 4,
    status: 'Confirmed',
    price: 3500000,
    referenceCode: 'VN-GLF-2023-XJ'
  },
  {
    id: 'b2',
    courseId: 'dn1',
    date: 'Nov 05, 2023',
    time: '07:30 AM',
    players: 4,
    status: 'Pending',
    price: 2200000,
    referenceCode: 'VN-GLF-2023-AA'
  }
];
